# Activité 2 : les bases de données  relationnelles

### activité 2.1
Soit la relation suivante :

<table>
			<tr>
				<th>
					id
				</th>
				<th>
					titre
				</th>
				<th>
					auteur
				</th>
				<th>
					ann_publi
				</th>
				<th>
					note
				</th>
			</tr>
			<tr>
				<td>
					1
				</td>
				<td>
					1984
				</td>
				<td>
					Orwell
				</td>
				<td>
					1949
				</td>
				<td>
					10
				</td>
			</tr>
			<tr>
				<td>
					2
				</td>
				<td>
					Dune
				</td>
				<td>
					Herbert
				</td>
				<td>
					1965
				</td>
				<td>
					8
				</td>
			</tr>
			<tr>
				<td>
					2
				</td>
				<td>
					Dune
				</td>
				<td>
					Herbert
				</td>
				<td>
					1965
				</td>
				<td>
					8
				</td>
			</tr>
			<tr>
				<td>
					3
				</td>
				<td>
					Fondation
				</td>
				<td>
					Asimov
				</td>
				<td>
					1951
				</td>
				<td>
					9
				</td>
			</tr>
			</table>
            
Faites la liste des éléments appartenant à l'attribut "auteur".

### activité 2.2
Soit la relation suivante :

<table>
			<tr>
				<th>
					id
				</th>
				<th>
					titre
				</th>
				<th>
					auteur
				</th>
				<th>
					ann_publi
				</th>
				<th>
					note
				</th>
			</tr>
			<tr>
				<td>
					1
				</td>
				<td>
					1984
				</td>
				<td>
					Orwell
				</td>
				<td>
					1949
				</td>
				<td>
					10
				</td>
			</tr>
			<tr>
				<td>
					2
				</td>
				<td>
					Dune
				</td>
				<td>
					Herbert
				</td>
				<td>
					1965
				</td>
				<td>
					8
				</td>
			</tr>
			<tr>
				<td>
					2
				</td>
				<td>
					Dune
				</td>
				<td>
					Herbert
				</td>
				<td>
					1965
				</td>
				<td>
					8
				</td>
			</tr>
			<tr>
				<td>
					3
				</td>
				<td>
					Fondation
				</td>
				<td>
					Asimov
				</td>
				<td>
					1951
				</td>
				<td>
					9
				</td>
			</tr>
			</table>

Quel est, selon vous, le domaine de l'attribut "auteur" ?

### activité 2.3

Voici un extrait d'une relation référençant des films :

<table>
			<caption style="text-align:center;">Relation FILMS</caption>
		<tr>
			<th>
				id
			</th>
			<th>
				titre
			</th>
			<th>
				realisateur
			</th>
			<th>
				ann_sortie
			</th>
			<th>
				note_sur_10
			</th>
		</tr>
		<tr>
			<td>
				1
			</td>
			<td>
				Alien, le huitième passager
			</td>
			<td>
				Scott
			</td>
			<td>
				1979
			</td>
			<td>
				10
			</td>
		</tr>
		<tr>
			<td>
				2
			</td>
			<td>
				Dune
			</td>
			<td>
				Lynch
			</td>
			<td>
				1985
			</td>
			<td>
				5
			</td>
		</tr>
		<tr>
			<td>
				3
			</td>
			<td>
				2001 : l'odyssée de l'espace
			</td>
			<td>
				Kubrick
			</td>
			<td>
				1968
			</td>
			<td>
				9
			</td>
		</tr>
		<tr>
			<td>
				4
			</td>
			<td>
				Blade Runner
			</td>
			<td>
				Scott
			</td>
			<td>
				1982
			</td>
			<td>
				10
			</td>
		</tr>
	</table>

Listez les différents attributs de cette relation. Donnez le domaine de chaque attribut.

Pour chaque attribut dire si cet attribut peut jouer le rôle de clef primaire, vous n'oublierez pas de justifier vos réponses.